drop table places cascade;

create table places (
                        id serial    primary key,
                        qr 			 varchar(256),
                        order_place  int,
                        coordinates  float[],
                        facilities   text[],
                        video_route  varchar(256),
                        tickets_link varchar(256),
                        tickets_text text,
                        cat          varchar(256),
                        visibility   varchar(256),
                        color        varchar(256),
                        color_code   varchar(256),
                        preview_text text,
                        detail_text  text,
                        title        varchar(256),
                        time_work    varchar(256),
                        type_place   varchar(256),
                        url          varchar(256),
                        pic          varchar(256),
                        code         varchar(256),
                        is_event	 bool,
                        electrobus_flag    bool,
                        scooter_flag       bool,
                        free                bool,
                        rating             int,
                        children_flag      bool,
                        date_flag          bool,
                        family_flag        bool,
                        animals_flag       bool,
                        bike_flag          bool,
                        promenade          bool,
                        activity          bool,
                        nature             bool,
                        science            bool,
                        national           bool,
                        workshop          bool,
                        creation          bool,
                        kids               bool,
                        tech               bool,
                        about_russia       bool,
                        type_service       varchar(16),
                        duration           int,
                        processed_preview  text,
                        processed_title    varchar(32),
                        vector_text        float[],
                        vector_title      float[],

);

create table place_event_sharing (
                        id serial primary key,
                        place_id int references places(id),
                        event_id int references places(id)
);
